#code generated by ChatGPT using prompt "write a simple program
# so I can write my own test cases based off of it"

#test cases are my own, this is not, although i understand this
#code completely

import random

def roll_dice():
    """Roll a six-sided die."""
    return random.randint(1, 6)


def calculate_damage(attack, defense):
    """Calculate damage dealt to an enemy."""
    damage = attack - defense

    if damage < 0:
        damage = 0

    return damage


def is_alive(health):
    """Return True if the character still has health."""
    return health > 0


def add_gold(current_gold, amount):
    """Add gold to the player's current amount."""
    return current_gold + amount


def buy_item(gold, item_cost):
    """Attempt to purchase an item and return the remaining gold."""
    if gold >= item_cost:
        return gold - item_cost

    return gold


def get_winner(player_health, enemy_health):
    """Determine the winner based on remaining health."""
    if player_health <= 0 and enemy_health <= 0:
        return "Draw"
    elif player_health <= 0:
        return "Enemy"
    elif enemy_health <= 0:
        return "Player"
    else:
        return "No winner yet"


def main():
    print("Welcome to the Dungeon Game!")

    player_health = 100
    enemy_health = 50
    player_attack = 20
    enemy_defense = 5

    roll = roll_dice()
    print(f"You rolled a {roll}!")

    damage = calculate_damage(player_attack, enemy_defense)
    enemy_health -= damage

    print(f"You dealt {damage} damage!")
    print(f"Enemy health: {enemy_health}")

    if not is_alive(enemy_health):
        print("You defeated the enemy!")
    else:
        print("The enemy is still alive!")


if __name__ == "__main__":
    main()